### ISSUE TITLE
Fluxo de Login de Admin

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#1]
Eu, adm - primeiro usuario do sistema - , consigo logar no sistema e cadastrar novos admin. 

Model Admin
   email, name, password

validar email com @codeplay.com.br

**Comment by JorgeLAB** [comment]
A prioridade poderia ser Cursos que é o core de inicio e depois realizariamos o processo de autenticação de usuários, ficariamos menos presos no início. Se realizar a criação do usuário no primeiro dia pode não fluir o/

**Comment by DanTupi** [comment]
concordo com o Jorge, mas como são 5 ou 6 duplas por dia no projeto, acredito que tudo bem fazer uns testes de autenticação, só acho que vamos precisar de algumas rotas para poder fazer os testes.

**Comment by jannilsonn** [comment]
Faz sentido pessoal criar um namespace para admin, e no caso seria assim?

```
namespace :admin do
    devise_for :admins 
    get 'admins', to: 'admins#index'
 end
```

**Comment by JorgeLAB** [comment]
Ficaria bacana mas o `devise_for :admins`  poderia ficar fora, porque geram rotas independentes:
```
devise_for :admins 

namespace :admin do
    get 'admins', to: 'admins#index'
 end
```

**Comment by JorgeLAB** [comment]
A path também seria redundante, incluindo o `devise_for :admins`  no `namespace` , ficaria : `new_*admin_admin*_session GET    /admin/admins/sign_in(.:format)`.
Também, talvez fuja do escopo desse card, mas no caso de um index de admins que você realizou, poderia ser `accounts` que nessa action viria todos os usuários e poderia filtrar por admins já que admin tem acesso a todos: 
```
namespace :admin do 
    get  'accounts', to: 'accounts#index' 
end 
``` 
Ficaria claro que só admin tem acesso a todas as contas e usar `accounts` tiraria a redundância de admin/admins ...

**Comment by jannilsonn** [comment]
A intensão é separar admin de usuário, e o devise ficar no escopo de admin. O nome do path está estranho mesmo, não sei como mudaria isso...

host  admin -> https://codeplay.com.br/admin
host user -> https://codeplay.com.br

Uma sugestão que implica em toda a aplicação.

**Comment by DanTupi** [comment]
Acredito que podemos abrir os routes do devise, mas é aquilo, não seria legal abrir.
Gostei da solução do Jorge de colocar um "accounts".

A questão toda destas rotas aqui foi porque queremos um index de usuários. Mas como não tem isso direto a gente precisava fazer.
MAS talvez a gente nem precise fazer este index pelo site, com uma view certinha... poderia ser só olhando banco de dados.

**Comment by diegormorais** [comment]
Time, na documentação do Devise encontramos a opção de gerar as views para user e admin separadas utilizando o parâmetro `config.scoped_views = true` no `config/initializers/devise.rb`. Acham interessante trabalharmos com essas views no projeto?

Fonte: https://github.com/heartcombo/devise#configuring-views

**Comment by jannilsonn** [comment]
Da pra resolver o problema das rotas assim.

```
namespace :admin do
    devise_scope :admins do
      get 'sign_in', to: 'devise/sessions#new'
      post 'sign_in', to: 'devise/sessions#create'
      delete 'sign_out', to: 'devise/sessions#destroy'
    end
 end
```
que ficaria assim

```
admin_sign_in GET    /admin/sign_in(.:format)  admin/devise/sessions#new
               POST   /admin/sign_in(.:format)  admin/devise/sessions#create
admin_sign_out DELETE /admin/sign_out(.:format) admin/devise/sessions#destroy
```

E para criar as views

`rails generate devise:views admins`
