### ISSUE TITLE
Pre-requisitos de cursos 

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#10]

**Comment by DanTupi** [comment]
A ideia deste card é colocar dentro do model dos cursos uma nova tabela com os conceitos e pré-requisistos necessários para fazer tal curso.
Pensando nisso agora, será que cabe também fazer uma nova tabela com "dificuldade" e colocar lá qual o grau de dificuldade tem o curso? iniciante, intermediário, avançado, sabem?

**Comment by JorgeLAB** [comment]
Acredito que quanto à dificuldade de um curso poderia ser apenas um campo `enum` listando-as na própria tabela de course. É um bom detalhe. 
A parte de requirements, acho que seria algo assim, uma outra tabela associando cursos: 
Com um atributo de referência a curso que é o `belongs_to` e o outro o required_course como um valor inteiro que é o `id` de outro curso. Mas estou pesquisando se uma `self join` seja um caminho melhor o/. Fica como sugestão para quem for fazer: 
![image](https://user-images.githubusercontent.com/41846128/115564197-a4456880-a28e-11eb-987d-31601acc1aed.png)
