### ISSUE TITLE
Visit Home page

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#13]
Eu, visitante, 
Gostaria de visitar a home da aplicação codeplay visualiazar ver um header com botão para cursos, planos, cadastro e realização de login.
Na home será possível visualizar conteúdos institucionais, uma prévia de alguns cursos em um carrossel e um campo para cadastro rápido, elém um footer para localização da empresa.

------------------------------------------------------------
Inserir template => https://technext.github.io/oneschool/index.html#teachers-section

**Comment by HenriqueMorato** [comment]
Esse card tá meio sem propósito, seria construir uma home? porque essa parte de login não casa tanto com ele.

**Comment by DanTupi** [comment]
Seria criar uma home mas já configurar a navbar no topo, com o acesso ao login e painel do usuário (se logado).
aqui não seria o card falando sobre login em si, mas já seria uma página "âncora" do projeto.
Acho que aqui seria legal já começar a colocar front, identidade visual, css em geral. E já ter algo para mostrar.

**Comment by GuiRokk** [comment]
Seria algo semelhante ao card de "Visitante abre o site" do promotion-system

**Comment by JorgeLAB** [comment]
Eu diria que o card é vago de inicio mais para uma plataforma de cursos a home é o núcleo das vendas, depois das funcionalidades principais seria ideal  dar atenção especial buscando um template e adequando outros card.
Como:
> Eu, usuário não autenticado, Gostaria de ter acesso a descrição e dados de um curso pela home.
> Eu, usuário não autenticado, Gostaria de ter acesso a uma lista de cursos de consulta. ( ou destaques e talvez o mesmo que o de cima )
> Eu, usuário não autenticado, Gostaria buscar um curso pela home.

.... e assim vai acho que vamos notar a necessidade com o tempo o/ ( Talvez tudo possa ser apenas um o/ ) 

A home de sites de cursos é comum não ser estática como portifólio mas vão direto ao ponto com feeds de cursos.
