### ISSUE TITLE
Cadastro e acesso dos alunos

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#2]
Eu visitante, gostaria de me cadastrar/logar como aluno na aplicação

**Comment by DanTupi** [comment]
a minha sugestão de texto:
eu, usuário registrado como aluno posso ver as aulas e cursos que comprei.

(daí a questão aqui seria autenticar e autorizar, e fazer aquela lista de cursos que o aluno comprou e está no "currículo" dele.

**Comment by GuiRokk** [comment]
A menos que esse card não se refira **_apenas_** ao ato de acessar a aplicação, como cadastro e login, minha sugestão para a "historia" do card, agregando ao que o @DanTupi comentou:

Eu, usuário visitante,
Gostaria de me cadastrar como aluno, e/ou fazer login
Uma vez registrado....
