### ISSUE TITLE
Index de cursos

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#3]
Eu, um usuário administrador autenticado no sistema, gostaria  de  ver todos os cursos

model Course
* Nome string
* Descrição text
* Professor string
* Valor decimal
* Token string

**Comment by JorgeLAB** [comment]
O título poderia ser "Criação de model curso" ou "Adição de model curso.".
- Acho também se colocar "CRUD curso" em outro card pode ficar "muita coisa"  para um par fazer ou muitas funcionalidade juntas, seria interessante desmenbrar.
     > Implementação de index curso # _no caso entra view, controller e testes_
     > Implementação de create curso # _no caso entra view new, controler e testes_     
     > Implementação de update curso # _view edit, controller e tests_ 
     > Implementação de delete curso  # _controller e tests_

Além de ter mais subdivisões de tarefas os commites ficam mais organizados o/, garante todos vão todar na modelagem de curso.

**Comment by JorgeLAB** [comment]
Lendo mais sobre o **Scrum**, o que falei aí na parte de cima é mais associado a Tasks ( deve fazer isso! Implemetar aquilo!). Essa parte de **Product Backlog Items** são mais evento como o Henrique fez no system-promotions _It is common to think of a Product Backlog Item as a User Story_ .
