### ISSUE TITLE
Colocando links na sidebar do admin

### ISSUE THREAD

**Issue by jannilsonn** [iugu-for-devs/codeplay#47]
Colocar links relacionados ao menu lateral "sidebar" no paiinel do admin.

- [x] Painel de controle
- [x] Membros
- [x] Cursos
- [x] Planos

Criar uma div com  avatar, nome e botão sair, no canto superior direito.

Um exemplo

![Captura de tela de 2021-04-26 17-50-12](https://user-images.githubusercontent.com/47226735/116149030-0996c080-a6b8-11eb-82d5-e317c822a493.png)

obs: sem o menu dropdown

**Comment by JorgeLAB** [comment]
o/ Bacana

**Comment by jannilsonn** [comment]
Além disso estou padronizado as views em questão de links e nomes dos botões

Antes estava: Nova membro
Mudei para: Cadastrar Membro

Usando o I18n
