### ISSUE TITLE
Usuário acessa seu perfil

### ISSUE THREAD

**Issue by lBenevides** [iugu-for-devs/codeplay#5]
Eu usuário aluno, consigo visitar meu perfil e ver meus dados de cadastro da conta, meus plano, meus cursos

**Comment by DanTupi** [comment]
minha  sugestão é:
"eu, aluno cadastrado, posso ver a lista de cursos que fiz, que comprei e gerir meus dados pessoais, formas de pagamento, nome, nome social, cursos que tenho interesse"
(esta parte de curso que tenho interesse pensei agora viajando aqui que ia ser legal ter aqueles tags "rails", "c", "scrum", etc nos cursos.)
