### ISSUE TITLE
Imagem de "cover não existente" corrompida

### ISSUE THREAD

**Issue by ghost** [iugu-for-devs/codeplay#59]
Eu, sistema, gostaria de exibir uma imagem padrão para quando não houver uma imagem de curso cadastrado

**Comment by DanTupi** [comment]
não estava aguentando isso e fiz na minha branch:

![image](https://user-images.githubusercontent.com/56041076/116463013-8b195a80-a840-11eb-96da-40c3adb71fa3.png)
