### ISSUE TITLE
Colocar logo na navbar

### ISSUE THREAD

**Issue by marcosantonio0307** [iugu-for-devs/codeplay#81]
Ter a logo da codeplay na navbar

**Comment by DanTupi** [comment]
Marcos, você consegue mudar o verdinho da logo para o roxinho do projeto que está agora? 
estamos usando  a cor: `#7971ea`

Por enquanto nossa nav bar e reformulação da home está assim:
![image](https://user-images.githubusercontent.com/56041076/116763846-57336600-a9f5-11eb-984e-da390e3ec7bf.png)
